### ISSUE TITLE
Move

### ISSUE THREAD

**Issue by Ramsal420** [ASLS-org/studio#46]
hello
I am unable to move objects/fixtures to desired location. I dont see any functions to move the components to the place i want.

**Comment by timekadel** [comment]
Hi @Ramsal420, in order to move selected fixtures around in the visualizer you'll need to toggle into transform control mode (https://studio.asls.timekadel.com/interface/visualizer/)  by hitting `T` (for translation) or `R` for rotation on your keyboard!
